blank_issues_enabled: true
contact_links:
  - name: KQL Documentation
    url: https://learn.microsoft.com/en-us/kusto/query/
    about: Learn more about Kusto Query Language (KQL) from the official Microsoft documentation.
